[project]
authors = [
    {name = "Frost Ming", email = "mianghong@gmail.com"},
]
include = "test.py"
requires-python = ">=3.6"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[tool]
[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    "idna; python_version=='3.6'",
    "chardet; python_version=='3.7'",
    "urllib3; python_version=='3.8'",
    "certifi; python_version=='3.9'",
    "pytz; python_version=='3.10'",
    "setuptools; python_version=='3.11'",
    "six; python_version=='3.12'",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
